spring.application.name=transfer

# Datasource com fallback para execução local
spring.datasource.url=jdbc:postgresql://localhost:5432/transfer_db
spring.datasource.username=postgres
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect