services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: picpay_db
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092